### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by chequille** [PIT-Solutions-Private-Limited/pits_tagcloud#1]
I am the first writing something here :-)

Unfortunatly, the extension is not working. No Tags ar shown in the frontend.
Using Typo3 7.6.15 and bootstrap_package.

Any idea why?
Regards,
Jürgen

**Comment by Minuts** [comment]
Hai,
Can you please check it again with the manual. I had got it working.
Did you include the extension in 'include static' section of the template record?

**Comment by chequille** [comment]
Hi Minu,Of course i included the static template. But can it be that your extension needs as well the css styled content static template? Because i do not use it.Regards Jürgen 



Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Minu Thomas <notifications@github.com> Datum: 03.03.17  09:16  (GMT+01:00) An: PIT-Solutions-Private-Limited/pits_tagcloud <pits_tagcloud@noreply.github.com> Cc: chequille <js@chequille.de>, Author <author@noreply.github.com> Betreff: Re: [PIT-Solutions-Private-Limited/pits_tagcloud] First Issue (#1) 
Hai,

Can you please check it again with the manual. I had got it working.

Did you include the extension in 'include static' section of the template record?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PIT-Solutions-Private-Limited/pits_tagcloud","title":"PIT-Solutions-Private-Limited/pits_tagcloud","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PIT-Solutions-Private-Limited/pits_tagcloud"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Minuts in #1: Hai,\r\nCan you please check it again with the manual. I had got it working.\r\nDid you include the extension in 'include static' section of the template record?"}],"action":{"name":"View Issue","url":"https://github.com/PIT-Solutions-Private-Limited/pits_tagcloud/issues/1#issuecomment-283893313"}}}

**Comment by chequille** [comment]
Hi Minu,
sorry, checked again verything but it is not working on my site.
Could it be, that some other extension is missing?
For Example the Extension Builder?

Did you try it on on your site with the bootstrap_package extension version 7.1.0 ?

Unfortunately, there is no error in the logs as far as I could see, so no chance to find the reason.

Maybe you have some other ideas.
Best regards,
Jürgen

**Comment by chequille** [comment]
Hi Minu,
I found the reason for the non working clous is bootstrap_package, because it disables all "CSS Stlyed Content" rendering. THereofre, without CSS Stlyed COntent static it is not working.

THereofre, I have to ask Benjamin (author from bootstrap_package) about this.

Best regards,
JÜrgen
